# Generated by Django 4.2.17 on 2025-04-21 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_propertyreview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='images',
        ),
    ]
